### ISSUE TITLE
ReadMe 오타

### ISSUE THREAD

**Issue by mike123789-dev** [nrurnru/PhotoMemo#1]
리드미 파일 23번째 줄
RST API에 오타가 있습니다 ㅎㅎ

PS. 프로젝트 구경 재밌게 하다 갑니다!
보니까 CoreData가 아니라 Realm를 쓰셨는데
이전에 CoreData과 비교해서 어땠나요??

**Comment by nrurnru** [comment]
ㅋㅋㅋㅋ아 바로 수정하러 갑니다😩
렘은 코어데이터보다 작성할 코드가 거의 없어서 확실히 편했어요!! 이게 라이브러리지!! 하는느낌??ㅋㅋㅋㅋ
근데 이번에 Rx 기반으로 쓰려니 반응형으로 처리할지 그냥 처리할지 고민되는 부분이 좀 있었습니다😂
